// Lista centralizada de nombres de monitores
export const NOMBRES_MONITORES = [
  "ANGIE NATALIA SANTANA ROJAS",
  "ASHLY CAICEDO",
  "DIANA MARULANDA",
  "FARUCK DAVID MEZU MINA",
  "JUAN DAVID ARANGO QUINTERO",
  "JUAN SEBASTIAN GARCIA",
  "KELLY VELAZCO AGRONO",
  "SILVANA BURITICA HOLGUIN",
  "MARCOS AMILKAR MURILLO AGAMEZ",
  "GISELLA MONTAÑO SOLIS",
  "SANTIAGO FERNANDO NACED ROJAS",
] as const

export type NombreMonitor = typeof NOMBRES_MONITORES[number]
